"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function SuggestionsPage() {
  const [suggestions, setSuggestions] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchSuggestions = async () => {
    setLoading(true);
    try {
      const response = await api.get("/brain/suggestions");
      setSuggestions(response);
    } catch (err) {
      console.error("Failed to load suggestions", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSuggestions();

    const handleRefresh = () => {
      fetchSuggestions();
    };

    window.addEventListener("data-updated", handleRefresh);
    return () => {
      window.removeEventListener("data-updated", handleRefresh);
    };
  }, [fetchSuggestions]);

  async function handleResolve(id: string, action: "approved" | "rejected") {
    try {
      await api.post(`/brain/suggestions/${id}/resolve?action=${action}`, {});
      // Remove from list
      setSuggestions(suggestions.filter((s: any) => s.id !== id));
    } catch (err) {
      console.error(`Failed to ${action} suggestion`, err);
    }
  }

  return (
    <div className="space-y-8 max-w-4xl pb-10">
      <div>
        <h2 className="text-3xl font-bold tracking-tight text-foreground">Smart Suggestions</h2>
        <p className="text-muted-foreground mt-2">
          Review suggestions generated by J.A.R.V.I.S. to better organize your workspaces and update beliefs.
        </p>
      </div>

      {loading ? (
        <div className="flex justify-center p-10"><span className="w-6 h-6 rounded-full border-2 border-primary border-t-transparent animate-spin"></span></div>
      ) : (
        <div className="grid grid-cols-1 gap-6">
          {suggestions.length === 0 && <p className="text-muted-foreground text-center p-10 border border-dashed border-white/10 rounded-xl">No pending suggestions.</p>}
          {suggestions.map((sug: any) => {
            const content = JSON.parse(sug.content);
            const isBelief = sug.suggestion_type === "new_belief";
            return (
              <Card key={sug.id} className="bg-black/40 backdrop-blur-md border-white/10 hover:border-primary/50 transition-colors shadow-xl">
                <CardHeader>
                  <div className="flex justify-between items-center">
                    <CardTitle className="text-lg text-foreground flex items-center gap-2">
                      <span className="w-2 h-2"></span>
                      {isBelief ? "New Belief Formed" : "Move Document"}
                    </CardTitle>
                    <Badge variant="outline" className="border-white/20 bg-background/50">Confidence: {sug.confidence}%</Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  {isBelief ? (
                    <p className="mb-2 text-foreground text-lg">
                      "{content.belief}"
                    </p>
                  ) : (
                    <>
                      <p className="mb-4 text-foreground text-lg">
                        J.A.R.V.I.S. noticed <span className="font-semibold text-primary">{content.filename}</span> appears related to <span className="font-semibold text-primary">{content.suggested_workspace}</span>.
                      </p>
                      {content.evidence && (
                        <div className="text-sm text-muted-foreground bg-black/20 border border-white/5 p-4 rounded-xl">
                          <p className="font-semibold mb-2 text-foreground uppercase tracking-wider text-xs">Evidence Found:</p>
                          <ul className="space-y-1">
                            {content.evidence.map((ev: string, idx: number) => (
                              <li key={idx} className="flex items-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-primary/50"></span>
                                {ev}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </>
                  )}
                </CardContent>
                <CardFooter className="flex justify-end space-x-3 border-t border-white/10 pt-4 bg-black/20 rounded-b-xl">
                  <Button variant="ghost" onClick={() => handleResolve(sug.id, "rejected")} className="hover:bg-destructive/20 hover:text-destructive">
                    Reject
                  </Button>
                  <Button onClick={() => handleResolve(sug.id, "approved")} className="shadow-lg shadow-primary/20">
                    Approve
                  </Button>
                </CardFooter>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}